spring:
  application:
    name: ManyToOne
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pramod#12
    url: jdbc:mysql://localhost:3306/manytoone
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
